'use strict';
/* ============================================================
   TENNIS SCOREKEEPER V1 — LÓGICA COMPLETA
   01 CONFIGURACIÓN | 02 INDEXEDDB | 03 ESTADO
   04 SCORE | 05 SAQUE | 06 EVENTOS | 07 STATS
   08 UNDO | 09 HISTORIAL | 10 NAVEGACIÓN | 11 PWA
   ============================================================ */
const DB='tennisDB',VER=1,STORE='matches';let dbp;const A={screen:'home',match:null,history:[],tab:'summary',search:''};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x)),other=p=>p?0:1,toast=m=>{let e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
function openDB(){return dbp||(dbp=new Promise((res,rej)=>{let r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}))}
async function put(x){let d=await openDB();return new Promise((res,rej)=>{let t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(x);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function all(){let d=await openDB();return new Promise((res,rej)=>{let r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function get(id){let d=await openDB();return new Promise((res,rej)=>{let r=d.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function del(id){let d=await openDB();return new Promise((res,rej)=>{let t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function ps(){return{aces:0,df:0,fsa:0,fsi:0,f1:0,ssa:0,ssi:0,s2:0,r1:0,r2:0,bw:0,bo:0,bs:0,w:0,ue:0,fe:0,wfh:0,wbh:0,wv:0,ufh:0,ubh:0,uv:0,ffh:0,fbh:0,fv:0,nw:0,np:0,pw:0,pl:0}}
function stats(){return{players:[ps(),ps()],points:0}}
function newMatch(c){let m={id:crypto.randomUUID(),players:[c.p1,c.p2],config:c,startAt:new Date().toISOString(),endAt:null,status:'active',sets:[],setIndex:0,current:{games:[0,0],points:[0,0],server:c.firstServer,serve:1,phase:'waiting',tb:false,stb:false,tbp:[0,0],tbFirst:null},setStats:[stats()],points:[],seq:0,undo:null,pointStart:null,actualFinal:null};return m}
/* ============================================================ 01 CONFIGURACIÓN ============================================================ */
let cfg={bestOf:3,deciding:'normal',stbTarget:10,stbRule:'win2',game:'advantage',firstServer:0};
let setupDraft={p1:'',p2:''};
function option(k,v,label){let s=cfg[k]===v?'selected':'';return `<button class="option ${s}" data-opt="${k}" data-val="${v}">${s?'<span class="ball">● </span>':''}${label}</button>`}
function setup(){return `<main class=app><div class=title>NUEVO PARTIDO</div><div class=card>
<label>JUGADOR 1</label><input id=p1 value="${esc(setupDraft.p1)}"><div class=section>JUGADOR 2</div><input id=p2 value="${esc(setupDraft.p2)}">
<div class=section>FORMATO</div><div class=opts>${option('bestOf',3,'MEJOR DE 3')}${option('bestOf',5,'MEJOR DE 5')}</div>
<div class=section>SET DECISIVO</div><div class=opts>${option('deciding','normal','NORMAL')}${option('deciding','stb','SUPER TIE-BREAK')}</div>
${cfg.deciding==='stb'?`<div class=section>SUPER TIE-BREAK</div><input id=target type=number min=1 value=${cfg.stbTarget}><div class=opts>${option('stbRule','win2','GANAR POR 2')}${option('stbRule','final','PUNTO FINAL')}</div>`:''}
<div class=section>PUNTUACIÓN DE GAME</div><div class=opts>${option('game','advantage','VENTAJA')}${option('game','golden','PUNTO DE ORO')}</div>
<div class=section>PRIMER SERVIDOR</div><div class=opts>${option('firstServer',0,'JUGADOR 1')}${option('firstServer',1,'JUGADOR 2')}</div>
<button class=big data-action=create>CREAR PARTIDO</button><button class=big data-action=started>PARTIDO COMENZADO</button><button class=big data-action=home>cancelar</button></div></main>`}
/* ============================================================ 02 SCORE + SERVE ============================================================ */
function gameLabel(p,g){if(cfg.game==='golden'){if(g[0]===g[1]&&g[0]>=3)return['40','40'];if(g[0]>=4)return['GAME',''];if(g[1]>=4)return['','GAME']}let l=['0','15','30','40'];if(g[0]<4&&g[1]<4)return[l[g[0]],l[g[1]]];if(g[0]===g[1])return['DEUCE','DEUCE'];if(g[0]===g[1]+1)return['AD','40'];if(g[1]===g[0]+1)return['40','AD'];return g[0]>g[1]?['GAME','']:['','GAME']}
function gw(m){let g=m.current.points;if(m.config.game==='golden'){if(g[0]>=4&&g[0]>g[1])return 0;if(g[1]>=4&&g[1]>g[0])return 1;return null}if(g[0]>=4&&g[0]-g[1]>=2)return 0;if(g[1]>=4&&g[1]-g[0]>=2)return 1;return null}
function setWinner(g){let h=Math.max(...g),l=Math.min(...g);if(h===6&&l<=4)return g[0]>g[1]?0:1;if(h===7&&(l===5||l===6))return g[0]>g[1]?0:1;return null}
function tbWinner(m){let p=m.current.tbp;if(m.current.stb){let t=m.config.stbTarget;if(m.config.stbRule==='final')return p[0]>=t?0:p[1]>=t?1:null;return p[0]>=t&&p[0]-p[1]>=2?0:p[1]>=t&&p[1]-p[0]>=2?1:null}return p[0]>=7&&p[0]-p[1]>=2?0:p[1]>=7&&p[1]-p[0]>=2?1:null}
function startTB(m,stb=false){m.current.tb=!stb;m.current.stb=stb;m.current.tbp=[0,0];m.current.tbFirst=m.current.server;m.current.serve=1;m.current.phase='waiting'}
function nextSet(m){let wins=[0,0];m.sets.forEach(s=>wins[s.score[0]>s.score[1]?0:1]++);let need=m.config.bestOf/2+.5;if(wins[0]>=need||wins[1]>=need){m.status='complete';m.endAt=new Date().toISOString();m.finalResult=result(m);m.undo=null;return}let nextServer=m.current.tbFirst!==null?other(m.current.tbFirst):m.current.server;m.setIndex=m.sets.length;m.current={games:[0,0],points:[0,0],server:nextServer,serve:1,phase:'waiting',tb:false,stb:false,tbp:[0,0],tbFirst:null};m.setStats[m.setIndex]=stats();if(m.setIndex===need-1&&m.config.deciding==='stb')startTB(m,true)}
function finishSet(m,w,stb){m.sets.push({score:stb?[...m.current.tbp]:[...m.current.games],isSTB:stb});nextSet(m)}
function scorePoint(m,w){let before=clone(m);before.undo=null;let pointStart=m.pointStart?clone(m.pointStart):before;pointStart.undo=null;m.undo=pointStart;let ss=m.setStats[m.setIndex],p=ss.players;let s=m.current.server,r=other(s);p[w].pw++;p[r].pl++;ss.points++;m.points.push({seq:++m.seq,server:s,receiver:r,serve:m.current.serve,winner:w,context:m.current.stb?'STB':m.current.tb?'TB':'GAME'});m.stats=m.setStats.reduce((a,x)=>{x.players.forEach((q,i)=>Object.keys(q).forEach(k=>a.players[i][k]+=q[k]));a.points+=x.points;return a},stats());
if(m.current.tb||m.current.stb){m.current.tbp[w]++;if(tbWinner(m)!==null)finishSet(m,w,m.current.stb);else{let n=m.current.tbp[0]+m.current.tbp[1];if(n===1)m.current.server=other(m.current.tbFirst);else if(n>1&&(n-1)%2===0)m.current.server=other(m.current.server)}m.current.serve=1;m.current.phase='waiting'}else{m.current.points[w]++;let g=gw(m);if(g!==null){m.current.games[g]++;m.current.points=[0,0];m.current.server=other(m.current.server);if(setWinner(m.current.games)!==null)finishSet(m,g,false);else if(m.current.games[0]===6&&m.current.games[1]===6)startTB(m,false)}m.current.serve=1;m.current.phase='waiting'}m.pointStart=clone(m);m.pointStart.undo=null;return save(m)}
/* ============================================================ 03 SAQUE + EVENTOS ============================================================ */
function breakPoint(m,r){if(m.current.tb||m.current.stb)return false;let g=m.current.points;if(m.config.game==='golden')return g[0]===3&&g[1]===3;return g[r]>=3&&g[r]>g[other(r)]}
function serve(m,type){let s=m.current.server,st=m.setStats[m.setIndex].players[s];if(m.current.serve===1&&!m.pointStart){m.pointStart=clone(m);m.pointStart.undo=null}if(m.current.serve===1)st.fsa++;else st.ssa++;if(type==='out'){if(m.current.serve===1){m.current.serve=2;return save(m)}st.df++;return scorePoint(m,other(s))}if(type==='ace'){if(m.current.serve===1){st.fsi++;st.f1++}else{st.ssi++;st.s2++}st.aces++;return scorePoint(m,s)}if(m.current.serve===1)st.fsi++;else st.ssi++;m.current.phase='in';return save(m)}
function event(m,player,e,stroke){
 /* EVENTO: player = jugador que ejecutó la acción.
    WINNER: el propio jugador gana el punto.
    ERROR NO FORZADO / FORZADO: el rival gana el punto. */
 let s=m.current.server,r=other(s),w=e==='w'?player:other(player),st=m.setStats[m.setIndex],p=st.players;
 if(m.current.serve===1){if(w===s)p[s].f1++;else p[r].r1++}else{if(w===s)p[s].s2++;else p[r].r2++}
 if(e==='w'){p[player].w++;p[player][stroke==='fh'?'wfh':stroke==='bh'?'wbh':'wv']++;if(stroke==='v'){p[player].nw++;p[player].np++}}
 else{let loser=player,key=e==='ue'?(stroke==='fh'?'ufh':stroke==='bh'?'ubh':'uv'):(stroke==='fh'?'ffh':stroke==='bh'?'fbh':'fv');p[loser][e==='ue'?'ue':'fe']++;p[loser][key]++;if(stroke==='v')p[loser].np++}
 if(breakPoint(m,r)){p[r].bo++;if(w===r){p[r].bw++}else p[s].bs++}
 return scorePoint(m,w)
}
/* ============================================================ 04 RENDER MATCH ============================================================ */
function result(m){return m.sets.map(s=>s.isSTB?`STB ${s.score[0]}–${s.score[1]}`:`${s.score[0]}–${s.score[1]}`).join(' / ')+(m.status==='active'?(m.current.stb?` / STB ${m.current.tbp[0]}–${m.current.tbp[1]}`:m.current.tb?` / ${m.current.games[0]}–${m.current.games[1]} TB ${m.current.tbp[0]}–${m.current.tbp[1]}`:`${m.sets.length?' / ':''}${m.current.games[0]}–${m.current.games[1]}`):'')}
function matchView(){let m=A.match,s=m.current,rows=m.sets.map(x=>`<div class=row><div>${x.score[0]}</div><div>${x.score[1]}</div></div>`).join('');if(s.stb)rows+=`<div class=row><div>${s.tbp[0]}</div><div>${s.tbp[1]}</div></div>`;else if(s.tb)rows+=`<div class=row><div>${s.games[0]}</div><div>${s.games[1]}</div></div><div class=row><div>${s.tbp[0]}</div><div>${s.tbp[1]}</div></div>`;else{let q=gameLabel(0,s.points);rows+=`<div class=row><div>${s.games[0]}</div><div>${s.games[1]}</div></div><div class=row><div>${q[0]}</div><div>${q[1]}</div></div>`}let serveBtns=p=>`<div class=label>${s.serve===1?'1.º':'2.º'} SAQUE</div><button class=action data-serve=ace>ACE</button><button class=action data-serve=in>ADENTRO</button><button class=action data-serve=out>AFUERA</button>`;let events=p=>['w','ue','fe'].map(e=>`<div class=label>${e==='w'?'WINNER':e==='ue'?'ERROR NO FORZADO':'ERROR FORZADO'}</div>${['fh','bh','v'].map((x,i)=>`<button class=action data-event=${e} data-player=${p} data-stroke=${x}>${['DERECHA','REVÉS','VOLEA'][i]}</button>`).join('')}`).join('');return `<main class=app><div class=score><div class=names><div>${esc(m.players[0])}</div><div>${esc(m.players[1])}</div></div>${rows}<div class=server><div>${s.server===0?'🟡':''}</div><div>${s.server===1?'🟡':''}</div></div><div class=actions><div class=util><button data-action=undo>deshacer</button><button data-action=stats>estadísticas</button></div><div class=actiongrid><div class=col>${s.phase==='in'?(events(0)):(s.server===0?serveBtns(0):'')}</div><div class=col>${s.phase==='in'?(events(1)):(s.server===1?serveBtns(1):'')}</div></div></div></div><div class=bottom><button data-action=finish>finalizar partido</button></div></main>`}
/* ============================================================ 05 STATS + HISTORIAL ============================================================ */
function agg(m){return m.setStats.reduce((a,x)=>{x.players.forEach((p,i)=>Object.keys(p).forEach(k=>a[i][k]+=p[k]));a.points+=x.points;return a},[ps(),ps(),0])}
function pct(a,b){return b?`${Math.round(a/b*100)}% (${a}/${b})`:'No registrado'}
function durationText(m){let start=Date.parse(m.startAt),end=m.endAt?Date.parse(m.endAt):Date.now();if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)return'No registrado';let min=Math.max(0,Math.round((end-start)/60000)),h=Math.floor(min/60),mm=min%60;return h?`${h} h ${mm.toString().padStart(2,'0')} min`:`${mm} min`}
function statsView(){let m=A.match||A.statsMatch;if(!m)return '<main class=app><div class=card>No hay estadísticas disponibles.</div><button class=big data-action=backstats>volver</button></main>';let a=agg(m),x=a[0],y=a[1],body=A.tab==='summary'?summary(m,x,y):A.tab==='sets'?setsView(m):strokes(m,x,y),resultAction=m.status==='partial'||m.actualFinal?`<button class=big data-action=addresult>${m.actualFinal?'EDITAR RESULTADO FINAL':'AGREGAR RESULTADO FINAL'}</button>`:'';return `<main class=app><div class=card><div class=title>${esc(m.players[0])} vs ${esc(m.players[1])}</div><div class=muted>${esc(m.actualFinal||m.finalResult||result(m))}</div><div class=muted>${m.status==='complete'?'🟢 COMPLETO':m.status==='active'?'🟢 PARTIDO EN CURSO':'🟡 ESTADÍSTICAS PARCIALES'} · ${a[2]} puntos registrados</div><div class=muted>Tiempo de juego: ${durationText(m)}</div>${resultAction}</div><div class=tabs><button class="${A.tab==='summary'?'selected':''}" data-tab=summary>RESUMEN</button><button class="${A.tab==='sets'?'selected':''}" data-tab=sets>POR SET</button><button class="${A.tab==='strokes'?'selected':''}" data-tab=strokes>GOLPES</button></div>${body}<button class=big data-action=copy>📋 COPIAR ESTA SECCIÓN</button><button class=big data-action=backstats>volver</button></main>`}
function row(n,a,b){return `<div class=srow><div>${n}</div><div>${a}</div><div>${b}</div></div>`}function stat(title,m,a,b,extra=''){return `<div class=stat><div class=stitle>${title}</div>${row('Aces',a.aces,b.aces)}${row('Dobles faltas',a.df,b.df)}${row('1.º saque',a.fsa?Math.round(a.fsi/a.fsa*100)+'%':'No registrado',b.fsa?Math.round(b.fsi/b.fsa*100)+'%':'No registrado')}${row('Puntos con 1.º saque',pct(a.f1,a.fsi),pct(b.f1,b.fsi))}${row('Puntos con 2.º saque',pct(a.s2,a.ssi),pct(b.s2,b.ssi))}${extra}</div>`}
function summary(m,a,b){return stat('SERVICE',m,a,b,row('Puntos ganados con 1.º saque del rival',pct(a.r1,b.fsi),pct(b.r1,a.fsi))+row('Puntos ganados con 2.º saque del rival',pct(a.r2,b.ssi),pct(b.r2,a.ssi)))+`<div class=stat><div class=stitle>BREAK POINTS</div>${row('Break points',pct(a.bw,a.bo),pct(b.bw,b.bo))}${row('Break points salvados',a.bs,b.bs)}</div>`+`<div class=stat><div class=stitle>PUNTOS</div>${row('Puntos ganados',pct(a.pw,m.stats.points),pct(b.pw,m.stats.points))}${row('Puntos en la red',pct(a.nw,a.np),pct(b.nw,b.np))}</div>`+strokes(m,a,b)}
function strokes(m,a,b){return [['WINNERS','w','wfh','wbh','wv'],['ERRORES NO FORZADOS','ue','ufh','ubh','uv'],['ERRORES FORZADOS','fe','ffh','fbh','fv']].map(z=>`<div class=stat><div class=stitle>${z[0]}</div>${row('Total',a[z[1]],b[z[1]])}${row('Derecha',a[z[2]],b[z[2]])}${row('Revés',a[z[3]],b[z[3]])}${row('Volea',a[z[4]],b[z[4]])}</div>`).join('')}
function setsView(m){return m.setStats.map((s,i)=>{let sa=s.players[0],sb=s.players[1],label=m.sets[i]?.isSTB?'SUPER TIE-BREAK':(i+1)+'.º SET',score=m.sets[i]?m.sets[i].score.join('–'):'EN CURSO';return `<div class=stat><div class=stitle>${label} ${score}</div>${row('Aces',sa.aces,sb.aces)}${row('Dobles faltas',sa.df,sb.df)}${row('1.º saque',sa.fsa?Math.round(sa.fsi/sa.fsa*100)+'%':'No registrado',sb.fsa?Math.round(sb.fsi/sb.fsa*100)+'%':'No registrado')}${row('Puntos con 1.º saque',pct(sa.f1,sa.fsi),pct(sb.f1,sb.fsi))}${row('Puntos con 2.º saque',pct(sa.s2,sa.ssi),pct(sb.s2,sb.ssi))}${row('Puntos ganados con 1.º saque rival',pct(sa.r1,sb.fsi),pct(sb.r1,sa.fsi))}${row('Puntos ganados con 2.º saque rival',pct(sa.r2,sb.ssi),pct(sb.r2,sa.ssi))}${row('Break points',pct(sa.bw,sa.bo),pct(sb.bw,sb.bo))}${row('Winners',sa.w,sb.w)}${row('Errores no forzados',sa.ue,sb.ue)}${row('Errores forzados',sa.fe,sb.fe)}${row('Puntos en la red',pct(sa.nw,sa.np),pct(sb.nw,sb.np))}${row('Puntos ganados',pct(sa.pw,s.points),pct(sb.pw,s.points))}</div>`}).join('')}
function historyView(){let q=A.search.toLowerCase(),arr=A.history.filter(m=>m.status!=='active'&&(!q||m.players.some(p=>p.toLowerCase().includes(q)))).sort((a,b)=>b.startAt.localeCompare(a.startAt));return `<main class=app><div class=title>HISTORIAL</div><input id=search placeholder="🔎 Buscar jugador..." value="${esc(A.search)}">${arr.map(m=>`<div class="card history" data-open=${m.id}><button class=delete data-del=${m.id}>eliminar</button><b>${esc(m.players[0])} vs ${esc(m.players[1])}</b><div>${esc(m.finalResult||result(m))}</div><div class=muted>${m.status==='complete'?'🟢 COMPLETO':'🟡 PARCIAL'} · ${new Date(m.startAt).toLocaleDateString('es-AR')}</div></div>`).join('')||'<div class=card>No hay partidos.</div>'}<button class=big data-action=home>volver</button></main>`}
/* ============================================================ 06 ROUTER / EVENTOS ============================================================ */
function render(){let r=$('#app');r.innerHTML=A.screen==='home'?home():A.screen==='setup'?setup():A.screen==='match'?matchView():A.screen==='stats'?statsView():historyView();bind()}
function home(){return `<main class=app><div class=title>TENNIS</div>${A.match?`<div class=card><b>PARTIDO PENDIENTE</b><p>${esc(A.match.players[0])} vs ${esc(A.match.players[1])}</p><p class=muted>${esc(result(A.match))}</p><button class=big data-action=continue>CONTINUAR PARTIDO</button><button class=big data-action=finish>FINALIZAR PARTIDO</button></div>`:''}<button class=big data-action=new>NUEVO PARTIDO</button><button class=big data-action=history>ESTADÍSTICAS</button></main>`}
function bind(){document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{setupDraft.p1=$('#p1')?.value||setupDraft.p1;setupDraft.p2=$('#p2')?.value||setupDraft.p2;let k=b.dataset.opt,v=b.dataset.val;cfg[k]=['bestOf','firstServer'].includes(k)?+v:v;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));document.querySelectorAll('[data-serve]').forEach(b=>b.onclick=()=>serve(A.match,b.dataset.serve));document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>event(A.match,+b.dataset.player,b.dataset.event,b.dataset.stroke));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{A.tab=b.dataset.tab;render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{A.statsMatch=await get(b.dataset.open);A.tab='summary';A.screen='stats';render()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async e=>{e.stopPropagation();if(confirm('¿Eliminar partido?')){await del(b.dataset.del);A.history=await all();render()}});let q=$('#search');if(q)q.oninput=()=>{A.search=q.value;render()}}
async function save(m){try{await put(m);A.match=m;render()}catch(e){toast('⚠️ NO SE PUDO GUARDAR EL PUNTO. El punto no fue registrado. Intentá nuevamente.')}}
function copyText(m,tab){let a=agg(m),A0=a[0],B0=a[1],lines=[`${m.players[0]} vs ${m.players[1]}`,m.actualFinal||m.finalResult||result(m),`Tiempo de juego: ${durationText(m)}`,''];if(tab==='summary'){lines.push('RESUMEN','',`ACES: ${A0.aces} | ${B0.aces}`,`DOBLES FALTAS: ${A0.df} | ${B0.df}`,`1.º SAQUE: ${A0.fsa?Math.round(A0.fsi/A0.fsa*100)+'%':'No registrado'} | ${B0.fsa?Math.round(B0.fsi/B0.fsa*100)+'%':'No registrado'}`,`PUNTOS CON 1.º SAQUE: ${pct(A0.f1,A0.fsi)} | ${pct(B0.f1,B0.fsi)}`,`PUNTOS CON 2.º SAQUE: ${pct(A0.s2,A0.ssi)} | ${pct(B0.s2,B0.ssi)}`,`PUNTOS GANADOS CON 1.º SAQUE RIVAL: ${pct(A0.r1,B0.fsi)} | ${pct(B0.r1,A0.fsi)}`,`PUNTOS GANADOS CON 2.º SAQUE RIVAL: ${pct(A0.r2,B0.ssi)} | ${pct(B0.r2,A0.ssi)}`,`BREAK POINTS: ${pct(A0.bw,A0.bo)} | ${pct(B0.bw,B0.bo)}`,`BREAK POINTS SALVADOS: ${A0.bs} | ${B0.bs}`,`WINNERS: ${A0.w} | ${B0.w}`,`ERRORES NO FORZADOS: ${A0.ue} | ${B0.ue}`,`ERRORES FORZADOS: ${A0.fe} | ${B0.fe}`,`PUNTOS EN LA RED: ${pct(A0.nw,A0.np)} | ${pct(B0.nw,B0.np)}`,`PUNTOS GANADOS: ${pct(A0.pw,a[2])} | ${pct(B0.pw,a[2])}`);}else if(tab==='sets'){lines.push('POR SET','');m.setStats.forEach((s,i)=>{let x=s.players[0],y=s.players[1],label=m.sets[i]?.isSTB?'SUPER TIE-BREAK':`${i+1}.º SET`,score=m.sets[i]?m.sets[i].score.join('–'):'EN CURSO';lines.push(`${label} ${score}`,`Aces: ${x.aces} | ${y.aces}`,`Dobles faltas: ${x.df} | ${y.df}`,`1.º saque: ${x.fsa?Math.round(x.fsi/x.fsa*100)+'%':'No registrado'} | ${y.fsa?Math.round(y.fsi/y.fsa*100)+'%':'No registrado'}`,`Puntos con 1.º saque: ${pct(x.f1,x.fsi)} | ${pct(y.f1,y.fsi)}`,`Puntos con 2.º saque: ${pct(x.s2,x.ssi)} | ${pct(y.s2,y.ssi)}`,`Winners: ${x.w} | ${y.w}`,`Errores no forzados: ${x.ue} | ${y.ue}`,`Errores forzados: ${x.fe} | ${y.fe}`,`Puntos en la red: ${pct(x.nw,x.np)} | ${pct(y.nw,y.np)}`,`Puntos ganados: ${pct(x.pw,s.points)} | ${pct(y.pw,s.points)}`,'');});}else{lines.push('GOLPES','',`WINNERS: ${A0.w} | ${B0.w}`,`  Derecha: ${A0.wfh} | ${B0.wfh}`,`  Revés: ${A0.wbh} | ${B0.wbh}`,`  Volea: ${A0.wv} | ${B0.wv}`,'',`ERRORES NO FORZADOS: ${A0.ue} | ${B0.ue}`,`  Derecha: ${A0.ufh} | ${B0.ufh}`,`  Revés: ${A0.ubh} | ${B0.ubh}`,`  Volea: ${A0.uv} | ${B0.uv}`,'',`ERRORES FORZADOS: ${A0.fe} | ${B0.fe}`,`  Derecha: ${A0.ffh} | ${B0.ffh}`,`  Revés: ${A0.fbh} | ${B0.fbh}`,`  Volea: ${A0.fv} | ${B0.fv}`);}return lines.join('\n');}
async function act(a){if(a==='new'){if(A.match){toast('TENÉS UN PARTIDO EN CURSO');return}cfg={bestOf:3,deciding:'normal',stbTarget:10,stbRule:'win2',game:'advantage',firstServer:0};setupDraft={p1:'',p2:''};A.screen='setup';render()}else if(a==='create'){setupDraft.p1=$('#p1').value.trim();setupDraft.p2=$('#p2').value.trim();let p1=setupDraft.p1,p2=setupDraft.p2;if(!p1||!p2){toast('Ingresá los dos jugadores');return}cfg.stbTarget=+($('#target')?.value||cfg.stbTarget);A.match=newMatch({...cfg,p1,p2});await put(A.match);A.screen='match';render()}else if(a==='history'){A.history=await all();A.screen='history';render()}else if(a==='home'){A.screen='home';render()}else if(a==='continue'){A.screen='match';render()}else if(a==='stats'){A.statsMatch=A.match;A.screen='stats';render()}else if(a==='backstats'){A.screen=A.statsMatch?.status==='active'?'match':'history';render()}else if(a==='undo'){if(A.match?.undo){A.match=clone(A.match.undo);A.match.undo=null;await put(A.match);render()}else toast('No hay un punto para deshacer')}else if(a==='finish'){if(A.match&&confirm('¿FINALIZAR PARTIDO?')){A.match.status='partial';A.match.endAt=new Date().toISOString();A.match.finalResult=result(A.match);A.match.undo=null;await put(A.match);A.match=null;A.screen='history';A.history=await all();render()}}else if(a==='copy'){let m=A.statsMatch||A.match,t=copyText(m,A.tab);try{await navigator.clipboard.writeText(t);toast('Sección copiada correctamente')}catch(e){toast('No se pudo copiar')}}}
/* ============================================================ 07 INICIO / RECUPERACIÓN ============================================================ */
(async()=>{await openDB();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});A.history=await all();A.match=A.history.find(x=>x.status==='active')||null;render()})();
/* ============================================================ 08 PRUEBAS BÁSICAS
   Ejecutar en consola: window.tennisTests()
   ============================================================ */
window.tennisTests=()=>{let ok=[];let add=(n,v)=>ok.push({test:n,ok:!!v});add('6-6 no es set final',!setWinner([6,6]));add('7-6 sí es final',setWinner([7,6])===0);add('8-6 no es final',setWinner([8,6])===null);let m=newMatch({p1:'A',p2:'B',bestOf:3,deciding:'normal',stbTarget:10,stbRule:'win2',game:'advantage',firstServer:0});add('A inicia saque',m.current.server===0);m.current.tb=true;m.current.tbp=[8,6];add('TB 8-6 termina',tbWinner(m)===0);let u=newMatch({p1:'A',p2:'B',bestOf:3,deciding:'normal',stbTarget:10,stbRule:'win2',game:'advantage',firstServer:0});serve(u,'out');add('Primer saque fallado pasa al segundo sin perder inicio',u.current.serve===2&&u.pointStart&&u.pointStart.current.serve===1);scorePoint(u,1);let uu=clone(u.undo);add('Undo de punto de segundo saque vuelve al primer saque',uu.current.serve===1);let z=newMatch({p1:'A',p2:'B',bestOf:3,deciding:'normal',stbTarget:10,stbRule:'win2',game:'advantage',firstServer:0});z.current.games=[6,4];z.current.server=0;finishSet(z,1,false);add('Nuevo set normal inicia quien NO saco el ultimo game',z.current.server===0);let t=newMatch({p1:'A',p2:'B',bestOf:3,deciding:'normal',stbTarget:10,stbRule:'win2',game:'advantage',firstServer:0});t.current.server=0;startTB(t,false);t.current.tbFirst=0;finishSet(t,0,false);add('Nuevo set tras TB inicia quien NO comenzo el TB',t.current.server===1);add('Error de jugador 0 da punto al rival',other(0)===1);add('Error de jugador 1 da punto al rival',other(1)===0);return ok};

/* ============================================================
   09B AJUSTES FINALES DE V1
   Partido comenzado + resultado posterior de parciales.
   ============================================================ */
let startedDraft={p1:'',p2:'',bestOf:3,deciding:'normal',stbTarget:10,stbRule:'win2',game:'advantage',sets:[],games:[0,0],server:0};
function startedView(){return `<main class=app><div class=title>PARTIDO COMENZADO</div><div class=card><label>JUGADOR 1</label><input id=sp1 value="${esc(startedDraft.p1)}"><div class=section>JUGADOR 2</div><input id=sp2 value="${esc(startedDraft.p2)}"><div class=section>FORMATO</div><div class=opts><button class="option ${startedDraft.bestOf===3?'selected':''}" data-startopt=bestOf data-v=3>MEJOR DE 3</button><button class="option ${startedDraft.bestOf===5?'selected':''}" data-startopt=bestOf data-v=5>MEJOR DE 5</button></div><div class=section>SETS FINALIZADOS</div><div>${startedDraft.sets.map((x,i)=>`<div class=grid2><input type=number min=0 max=7 data-sa=${i} value=${x[0]}><input type=number min=0 max=7 data-sb=${i} value=${x[1]}></div>`).join('')}</div><button class=big data-action=addset>+ AGREGAR SET</button><div class=section>SET ACTUAL</div><div class=grid2><input id=cg0 type=number min=0 value=${startedDraft.games[0]}><input id=cg1 type=number min=0 value=${startedDraft.games[1]}></div><div class=section>${startedDraft.games[0]===6&&startedDraft.games[1]===6?'¿QUIÉN SACA EL PRIMER PUNTO DEL TIE-BREAK?':'¿QUIÉN SACA EL PRÓXIMO GAME?'}</div><div class=opts><button class="option ${startedDraft.server===0?'selected':''}" data-startopt=server data-v=0>JUGADOR 1</button><button class="option ${startedDraft.server===1?'selected':''}" data-startopt=server data-v=1>JUGADOR 2</button></div><button class=big data-action=startstarted>COMENZAR REGISTRO</button><button class=big data-action=home>cancelar</button></div></main>`}
const _render=render;render=function(){let r=$('#app');r.innerHTML=A.screen==='home'?home():A.screen==='setup'?setup():A.screen==='started'?startedView():A.screen==='match'?matchView():A.screen==='stats'?statsView():historyView();bind()};
const _bind=bind;bind=function(){_bind();document.querySelectorAll('[data-startopt]').forEach(b=>b.onclick=()=>{startedDraft.p1=$('#sp1')?.value||startedDraft.p1;startedDraft.p2=$('#sp2')?.value||startedDraft.p2;startedDraft.games=[+($('#cg0')?.value||startedDraft.games[0]),+($('#cg1')?.value||startedDraft.games[1])];startedDraft[b.dataset.startopt]=+b.dataset.v;render()})};
const _act=act;act=async function(a){
 if(a==='started'){startedDraft={p1:'',p2:'',bestOf:3,deciding:'normal',stbTarget:10,stbRule:'win2',game:'advantage',sets:[],games:[0,0],server:0};A.screen='started';render();return}
 if(a==='addset'){startedDraft.p1=$('#sp1')?.value||startedDraft.p1;startedDraft.p2=$('#sp2')?.value||startedDraft.p2;startedDraft.games=[+($('#cg0')?.value||startedDraft.games[0]),+($('#cg1')?.value||startedDraft.games[1])];startedDraft.sets=startedDraft.sets.map((x,i)=>[+document.querySelector(`[data-sa=\"${i}\"]`)?.value||x[0],+document.querySelector(`[data-sb=\"${i}\"]`)?.value||x[1]]);startedDraft.sets.push([0,0]);render();return}
 if(a==='startstarted'){
  const p1=$('#sp1').value.trim(),p2=$('#sp2').value.trim();
  if(!p1||!p2){toast('Ingresá los dos jugadores');return}
  const sets=startedDraft.sets.map((_,i)=>[+document.querySelector(`[data-sa="${i}"]`).value,+document.querySelector(`[data-sb="${i}"]`).value]);
  const valid=s=>{let h=Math.max(s[0],s[1]),l=Math.min(s[0],s[1]);return h===6&&l<=4||h===7&&(l===5||l===6)};
  if(sets.some(s=>!valid(s))){toast('Hay un set finalizado inválido');return}
  const need=startedDraft.bestOf/2+.5,w=[0,0];sets.forEach(s=>w[s[0]>s[1]?0:1]++);if(w[0]>=need||w[1]>=need){toast('Los sets cargados ya terminan el partido');return}
  let m=newMatch({p1,p2,bestOf:startedDraft.bestOf,deciding:startedDraft.deciding,stbTarget:startedDraft.stbTarget,stbRule:startedDraft.stbRule,game:startedDraft.game,firstServer:startedDraft.server});
  m.sets=sets.map((score,i)=>({score,isSTB:false}));m.setIndex=sets.length;m.setStats=sets.map(()=>stats());m.setStats.push(stats());m.current.games=[+$('#cg0').value,+$('#cg1').value];m.current.server=startedDraft.server;m.current.serve=1;m.current.phase='waiting';
  if(m.current.games[0]===6&&m.current.games[1]===6)startTB(m,false);
  await put(m);A.match=m;A.screen='match';render();return;
 }
 if(a==='addresult'){
  if(!A.statsMatch||A.statsMatch.status!=='partial')return;
  const r=prompt('Resultado final (ejemplo: 6-4 / 6-3):',A.statsMatch.actualFinal||A.statsMatch.finalResult||'');
  if(!r)return;
  const clean=r.trim().replace(/\s+/g,' ').replace(/-/g,'–');
  if(!/^[0-9]+–[0-9]+(?:\s*\/\s*(?:[0-9]+–[0-9]+|STB\s+[0-9]+–[0-9]+))*$/i.test(clean)){toast('Formato inválido. Usá por ejemplo: 6-4 / 6-3');return}
  A.statsMatch.actualFinal=clean;A.statsMatch.finalResult=clean;await put(A.statsMatch);A.history=await all();render();return;
 }
 return _act(a);
};
